const EUROPE_SERVER = 20
const ONE_V_ONE_GAMEMODE = '1'
const TWO_V_TWO_GAMEMODE = '2'
const FOUR_V_FOUR_GAMEMODE = '4'
const FOUR_V_FOUR_AT_GAMEMODE = '8'
const TWO_V_TWO_AT_GAMEMODE = '6'
const ONE_V_ONE_ROC_GAMEMODE = '301'
const ONE_V_ONE_LEGION_TD = '203'
const FOUR_V_FOUR_LEGION_TD = '202'
const DIRECT_STRIKE_GAMEMODE = '1101'
const DIRECT_STRIKE_AT_GAMEMODE = '1102'
const MINIDOTA_GAMEMODE = '1501'
const MINIDOTA_AT_GAMEMODE = '1502'
const RANDOM_HERO_GAMEMODE = '601'
const SURVIVAL_CHAOS_GAMEMODE = '1001'
const CASTLE_FIGHT_GAMEMODE = '1301'

const ONE_V_ONE_GAMEMODE_NAME = '1 VS 1'
const TWO_V_TWO_GAMEMODE_NAME = '2 VS 2'
const FOUR_V_FOUR_GAMEMODE_NAME = '4 VS 4'
const FOUR_V_FOUR_AT_GAMEMODE_NAME = '4 VS 4 AT'
const TWO_V_TWO_AT_GAMEMODE_NAME = '2 VS 2 AT'
const ONE_V_ONE_ROC_GAMEMODE_NAME = 'RoC 1 VS 1'
const ONE_V_ONE_LEGION_TD_NAME = 'Legion TD 1 VS 1'
const FOUR_V_FOUR_LEGION_TD_NAME = 'Legion TD 4 VS 4'
const DIRECT_STRIKE_GAMEMODE_NAME = 'DIRECT STRIKE 3 VS 3'
const DIRECT_STRIKE_AT_GAMEMODE_NAME = 'DIRECT STRIKE AT 3 VS 3'
const MINIDOTA_GAMEMODE_NAME = 'MINIDOTA 3 VS 3'
const MINIDOTA_AT_GAMEMODE_NAME = 'MINIDOTA AT 3 VS 3'
const RANDOM_HERO_GAMEMODE_NAME = 'RANDOM HERO'
const SURVIVAL_CHAOS_GAMEMODE_NAME = 'SURVIVAL CHAOS'
const CASTLE_FIGHT_GAMEMODE_NAME = 'CASTLE FIGHT'

const GAMEMODES = {
  [ONE_V_ONE_GAMEMODE]: ONE_V_ONE_GAMEMODE_NAME,
  [TWO_V_TWO_GAMEMODE]: TWO_V_TWO_GAMEMODE_NAME,
  [FOUR_V_FOUR_GAMEMODE]: FOUR_V_FOUR_GAMEMODE_NAME,
  [FOUR_V_FOUR_AT_GAMEMODE]: FOUR_V_FOUR_AT_GAMEMODE_NAME,
  [ONE_V_ONE_ROC_GAMEMODE]: ONE_V_ONE_ROC_GAMEMODE_NAME,
  [ONE_V_ONE_LEGION_TD]: ONE_V_ONE_LEGION_TD_NAME,
  [FOUR_V_FOUR_LEGION_TD]: FOUR_V_FOUR_LEGION_TD_NAME,
  [MINIDOTA_GAMEMODE]: MINIDOTA_GAMEMODE_NAME,
  [MINIDOTA_AT_GAMEMODE]: MINIDOTA_AT_GAMEMODE_NAME,
  [DIRECT_STRIKE_GAMEMODE]: DIRECT_STRIKE_GAMEMODE_NAME,
  [DIRECT_STRIKE_AT_GAMEMODE]: DIRECT_STRIKE_AT_GAMEMODE_NAME,
  [RANDOM_HERO_GAMEMODE]: RANDOM_HERO_GAMEMODE_NAME,
  [SURVIVAL_CHAOS_GAMEMODE]: SURVIVAL_CHAOS_GAMEMODE_NAME,
  [TWO_V_TWO_AT_GAMEMODE]: TWO_V_TWO_AT_GAMEMODE_NAME,
  [CASTLE_FIGHT_GAMEMODE]: CASTLE_FIGHT_GAMEMODE_NAME,
}

const RACES = {
  1: 'HUM',
  2: 'ORC',
  4: 'NE',
  8: 'UD',
  0: 'RDM'
}



function helperBattleTag(player) {
  const str = player.split("%");
  const playerNameEncode = encodeURIComponent(str[0]);
  return `${playerNameEncode}%${str[1]}`;
}

function displayWinrate(winrate) {
  const percentageFormat = new Intl.NumberFormat("en-US", {
    style: "percent",
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  }).format(winrate);
  return percentageFormat;
}

module.exports = {
  helperBattleTag,
  displayWinrate,
  EUROPE_SERVER,
  ONE_V_ONE_GAMEMODE,
  TWO_V_TWO_GAMEMODE,
  FOUR_V_FOUR_GAMEMODE,
  ONE_V_ONE_ROC_GAMEMODE,
  ONE_V_ONE_LEGION_TD,
  FOUR_V_FOUR_LEGION_TD,
  MINIDOTA_GAMEMODE,
  ONE_V_ONE_GAMEMODE_NAME,
  TWO_V_TWO_GAMEMODE_NAME,
  FOUR_V_FOUR_GAMEMODE_NAME,
  FOUR_V_FOUR_AT_GAMEMODE_NAME,
  FOUR_V_FOUR_AT_GAMEMODE,
  ONE_V_ONE_ROC_GAMEMODE_NAME,
  ONE_V_ONE_LEGION_TD_NAME,
  FOUR_V_FOUR_LEGION_TD_NAME,
  MINIDOTA_GAMEMODE_NAME,
  MINIDOTA_AT_GAMEMODE_NAME,
  MINIDOTA_AT_GAMEMODE,
  DIRECT_STRIKE_GAMEMODE,
  DIRECT_STRIKE_GAMEMODE_NAME,
  GAMEMODES,
  RACES
};
